# Cloudflare Workers configuration for SwapWatch API

name = "swapwatch-api"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Environment configuration
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Durable Objects binding
[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDurableObject"
script_name = "swapwatch-api"

# KV Namespace for room index
[[kv_namespaces]]
binding = "ROOM_INDEX"
id = "your-kv-namespace-id" # Will be created on first deploy

# Routes (will activate once DNS propagates and Worker is deployed)
# [[routes]]
# pattern = "api.swapwatch.app/*"
# zone_name = "swapwatch.app"

# Build configuration
[build]
command = "pnpm build:worker"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Secrets (set via wrangler secret)
# COINBASE_WEBHOOK_SECRET
# TELEGRAM_BOT_TOKEN
# DEXSCREENER_API_KEY
# BASESCAN_API_KEY