name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'src/worker/**'
      - 'src/services/**'
      - 'src/infrastructure/**'
      - 'src/types/**'
      - 'src/utils/**'
      - 'src/middleware/**'
      - 'wrangler.toml'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/deploy-worker.yml'
  workflow_dispatch:

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    name: Deploy API Worker to Cloudflare

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Type check Worker
        run: pnpm run build:worker

      - name: Deploy to Cloudflare Workers (Production)
        run: pnpm run deploy:worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
